name: EOL Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
permissions:
  issues: write
  contents: read

jobs:
  eol-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Check EOL and create issue
        run: |
          python -c "
          import sys, json
          sys.path.append('src')
          from eol_checker import EOLChecker
          from file_handlers import load_tools_from_json, save_results_html
          
          tools = load_tools_from_json('data/input/tools.json')
          results = EOLChecker().check_multiple_tools(tools)
          html_report = save_results_html(results)
          
          eol_tools = [r for r in results if r['eol_status'] == 'EOL']
          if eol_tools:
              with open('eol_issue.md', 'w') as f:
                  f.write('## 🚨 EOL Tools Detected\\n\\n')
                  f.write(f'[📊 Download Full HTML Report](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})\\n\\n')
                  for tool in eol_tools:
                      f.write(f'- **{tool[\"tool_name\"]} {tool[\"current_version\"]}** - EOL: {tool[\"eol_date\"]}\\n')
          else:
              with open('close_issue.md', 'w') as f:
                  f.write('✅ All tools are now supported! No EOL tools detected. Closing this issue.\\n')
          "

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: eol-html-report
          path: data/output/reports/eol_report.html

      - name: Install GitHub CLI
        if: hashFiles('close_issue.md') != ''
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Create issue if EOL found
        if: hashFiles('eol_issue.md') != ''
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "EOL Tools Detected"
          content-filepath: eol_issue.md
          labels: eol,dependencies