name: EOL Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  issues: write
  contents: read
  pull-requests: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  eol-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate EOL report
        run: |
          python run.py --input data/input/tools.json --output-dir data/output/reports

      - name: Upload HTML Report artifact
        uses: actions/upload-artifact@v4
        with:
          name: eol-html-report
          path: data/output/reports/*.html
          retention-days: 7

      - name: Install GitHub CLI and jq
        run: |
          type -p gh >/dev/null || sudo apt update && sudo apt install -y gh
          sudo apt-get install -y jq

      - name: Create GitHub issues for critical and warning tools
        run: |
          python scripts/create_issues_python.py
        env:
          GH_TOKEN: ${{ github.token }}